version: '2'

services:
  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elkstack
  kibana:
    build:
      context: kibana
      dockerfile: Dockerfile
    ports:
      - "5601:5601"
    networks:
      - elkstack
    depends_on:
      - elasticsearch
  logstash:
    build:
      context: logstash
      dockerfile: Dockerfile
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - elkstack
    depends_on:
      - elasticsearch

networks:
  elkstack:
    driver: bridge